Feature: Change Pin

#  Customers being issued new cards are supplied with a personal Identification Number (PIN)
#  that is randomly generated by the system.
#  In order to be able to change it to something they can easily remember,
#  customers with new bank cards need to be able to change their PIN using the ATM.


#  Scenario: Change PIN successfully
#    Given I have been issued a new card
#    And I insert the card, entering the correct PIN
#    When I choose "Change PIN" from the menu
#    And I change the PIN to 9876
#    Then the system should remember my PIN is now 9876
#
#  Scenario: Try to change PIN to the same as before
#    Given I have been issued a new card
#    And I insert the card, entering the correct PIN
#    When I choose "Change PIN" from the menu
#    And I try to change the PIN to the original PIN number
#    Then I should see a warning message
#    And the system should not have changed my PIN

  #換一個版本來描述，利用Background 的效果

  As soon as the bank issues new cards to customers, they are supplied with a Personal identification number (PIN),
  that is randomly generated by the system.
  In order to be able to change it to something they can easily remember,
  customers with new bank cards need to be able to change their PIN using the ATM.

  Background:
    Given I have been issued a new card
    And I insert the card, entering the correct PIN
    And I choose "Change PIN" from the menu


  Scenario: Change PIN successfully
    When I change the PIN to 9876
    Then the system should remember my PIN is now 9876

  Scenario: Try to change PIN to the same as before
    When I try to change the PIN to the original PIN number
    Then I should see a warning message
    And the system should not have changed my PIN

  #這個改過後的版本，比較容易有彙整需求的內含在，讀取理解上也變得容易得多

  #書上的介紹是講到說，每一個Background 都可以放到一個 feature file 去單獨存放，這樣就可以改一次就吃全部!!
  #我們何時會用到Background ? 答案是重構你的 feature files !!!
